blueprint:
  name: IKEA E2001/E2002 - STYRBAR remote control
  description: Use the IKEA E2001/E2002 remote control
  domain: automation
  input:
    remote:
      name: Remote
      description: Select the remote
      selector:
        device:
          multiple: false
    target_light:
      name: Light
      description: Select the light the should be turned on/off
      selector:
        entity:
          domain: light
    button_right:
      name: Actie voor up
      default: []
      selector:
        action: {}
    button_left:
      name: Action for down
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action
variables:
  brightness_step: 5       # % per loop iteration
  loop_interval: 0.15      # seconds (150ms)
  dimming_active: false

action:
  - variables:
      action: "{{ trigger.payload }}"
  - choose:
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light

      # UP hold -> start increasing brightness smoothly
      - conditions: "{{ action == 'brightness_move_up' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
          - repeat:
              while:
                - condition: template
                  value_template: "{{ not is_state(trigger.entity_id, 'brightness_stop') }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input target_light
                  data:
                    brightness_step_pct: "{{ brightness_step }}"
                - delay:
                    seconds: "{{ loop_interval }}"

      # DOWN hold -> start decreasing brightness smoothly
      - conditions: "{{ action == 'brightness_move_down' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
          - repeat:
              while:
                - condition: template
                  value_template: "{{ not is_state(trigger.entity_id, 'brightness_stop') }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input target_light
                  data:
                    brightness_step_pct: "-{{ brightness_step }}"
                - delay:
                    seconds: "{{ loop_interval }}"

      # RELEASE -> stop dimming
      - conditions: "{{ action == 'brightness_stop' }}"
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: !input target_light

      - conditions: "{{ action == 'arrow_left_click' }}"
        sequence: !input button_left

      - conditions: "{{ action == 'arrow_right_click' }}"
        sequence: !input button_right
        