blueprint:
  name: IKEA E2001/E2002 (MQTT) - Light Control + Extra Actions
  description: |
    Gebruik de IKEA E2001/E2002 afstandsbediening (Zigbee2MQTT via MQTT).
    - UP  (on)  → schakelt geselecteerd licht AAN
    - DOWN (off) → schakelt geselecteerd licht UIT
    - LEFT  (arrow_left_click)  → vrije actie
    - RIGHT (arrow_right_click) → vrije actie

  domain: automation

  input:
    remote:
      name: IKEA Remote
      description: Selecteer de IKEA E2001/E2002 remote (Zigbee2MQTT device)
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA of Sweden
          model: TRADFRI remote control

    target_light:
      name: Licht
      description: Selecteer het licht dat Up/Down moet bedienen
      selector:
        entity:
          domain: light

    button_left:
      name: Actie voor LEFT (arrow_left_click)
      default: []
      selector:
        action: {}

    button_right:
      name: Actie voor RIGHT (arrow_right_click)
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action

action:
  - variables:
      action: "{{ trigger.payload }}"

  - choose:
      # UP button → on → turn light ON
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      # DOWN button → off → turn light OFF
      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light

      # LEFT button → custom action
      - conditions: "{{ action == 'arrow_left_click' }}"
        sequence: !input button_left

      # RIGHT button → custom action
      - conditions: "{{ action == 'arrow_right_click' }}"
        sequence: !input button_right
