blueprint:
  name: IKEA E2001/E2002 - STYRBAR remote control
  description: Use the IKEA E2001/E2002 remote control
  domain: automation
  input:
    remote:
      name: Remote
      description: Select the remote
      selector:
        device:
          multiple: false
    target_light:
      name: Light
      description: Select the light the should be turned on/off
      selector:
        entity:
          domain: light
    button_right:
      name: Actie voor up
      default: []
      selector:
        action: {}
    button_left:
      name: Action for down
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action
action:
  - variables:
      action: "{{ trigger.payload }}"
  - choose:
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light

      - conditions: "{{ action == 'brightness_move_up' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: 10
              transition: 30

      - conditions: "{{ action == 'brightness_move_down' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: -10
              transition: 30

      - conditions: "{{ action == 'brightness_stop' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              transition: 0

      - conditions: "{{ action == 'arrow_left_click' }}"
        sequence: !input button_left

      - conditions: "{{ action == 'arrow_right_click' }}"
        sequence: !input button_right
        