blueprint:
  name: IKEA E2001/E2002 - STYRBAR remote control
  description: Use the IKEA E2001/E2002 remote control via Zigbee2MQTT (entity-based)
  domain: automation
  input:
    remote_action_sensor:
      name: Remote Action Sensor
      description: Select the Zigbee2MQTT action sensor for your remote (e.g. sensor.ikea_remote_action)
      selector:
        entity:
          domain: sensor
    target_light:
      name: Light
      description: Select the light to control
      selector:
        entity:
          domain: light
    button_right:
      name: Action for right button (up)
      default: []
      selector:
        action: {}
    button_left:
      name: Action for left button (down)
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote_action_sensor

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
  - choose:
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light

      - conditions: "{{ action == 'arrow_left_click' }}"
        sequence: !input button_left

      - conditions: "{{ action == 'arrow_right_click' }}"
        sequence: !input button_right
